[build]
    publish = "hugo-tania/exampleSite/public"
    command = "mkdir -p hugo-tania; mv ./* hugo-tania/; cd hugo-tania; yarn; yarn build"

[build.environment]
    GO_VERSION = "1.22.0"
    HUGO_VERSION = "0.130.0"