baseurl: "https://example.com"
languageCode: "en-us"
title: "Hugo Tania"
theme: "hugo-tania"

pagination:
  pagerSize: 6

disqusShortname: https-hugo-tania-netlify-app

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji:

  # Logo will show before the blog title on site navbar.
  titleLogo: favicon.ico
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  
  siteName: "Hugo Tania is Amazing"
  siteDesc: "Hugo is Absurdly Fast!"
  author: "Hugo Tania"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    github:
      # required The icon vendor and name, e.g. fab github, fas envelope.
      icon: "fab github" 
      # required The url of social link.
      url: "https://github.com/fordes123"
      # optional The color of icon, e.g. blue, red, #FF438A.
      color: currentColor 
      # optional The weight of the social link, default to 0.
      weight: 1
    email:
      icon: "fas envelope"
      url: "mailto:noreply@example.org"
  
  # Comments settings
  comments:
    enabled: true
    provider: giscus

    giscus:
      repo: fordes123/hugo-tania
      id: R_kgDONempBw
      category:
        name: Comments
        id: DIC_kwDONempB84ClSYL

  # Date format
  dateFormat:
    # Default to "Jan 02"
    archive: "01-02"
    # Default to "Jan 02, 2006"
    single: "2006, 01-02"

  # Hide the title in the header
  hiddenTitleInHeader: false

menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true
    extensions:
      table: true

outputs:
  home: ["HTML", "RSS", "JSON"]