baseurl = "https://example.com"
languageCode = "en-us"
title = "Hugo Tania"
theme = "hugo-tania"
paginate = 6

disqusShortname = "https-hugo-tania-netlify-app"

[params]
  # Emoji will show before the blog title on site navbar.
  titleEmoji  = "😎"

  # Logo will show before the blog title on site navbar.
  titleLogo = ""

  # Enable float footnotes.
  # Default to true
  enableFootnotes = true

  siteName = "Hugo Tania is Amazing"
  siteDesc = "Hugo is Absurdly Fast!"
  author = "Hugo Tania"

  [params.colorScheme]
    # Enable toggle colorScheme
    # Default to true
    toggle = true
    # Default colorScheme
    # Default to auto
    default = auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10

  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    [params.socialOptions.github]
    # The icon vendor and name, e.g. fab github, fas envelope
    icon = "fab github"
    # The url of social link
    url = "https://github.com/fordes123"
    # The color of icon, e.g. blue, red, #FF438A
    color = "currentColor"
    
    [params.socialOptions.email]
    # The icon vendor and name, e.g. fab github, fas envelope
    icon = "fas envelope"
    # The url of social link
    url = "mailto:noreply@example.org"

  # Comments settigns
  [params.comments]
    enabled = true
    provider = "disqus"

[menu]
[[menu.header]]
  name = "Articles"
  url = "/articles/"
[[menu.footer]]
    name = "RSS"
    url = "/index.xml"

[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]